kind: pipeline
type: docker
name: default
platform:
    os:   linux
    arch: arm64

steps:
    -   name:  restore cache
        image: meltwater/drone-cache
        settings:
            pull:    true
            backend: "filesystem"
            restore: true
            #            cache_key:      "volume"
            #            archive_format: "gzip"
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache

    -   name:  npm install
        image: node:18-alpine
        when:
            branch:
                - main
        commands:
            - npm ci

    -   name:  release
        image: node:18-alpine
        when:
            branch:
                - main
        environment:
            GH_TOKEN:
                from_secret: GH_TOKEN
        commands:
            - apk update && apk upgrade && apk add --no-cache git
            - npm run semantic-release

    -   name:  rebuild cache
        image: meltwater/drone-cache
        settings:
            pull:    true
            backend: "filesystem"
            rebuild: true
            #cache_key:      "volume"
            #archive_format: "gzip"
            # filesystem_cache_root: "/tmp/cache"
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache
        when:
            status:
                - success
                - failure
                -
volumes:
    -   name: cache
        host:
            path: /mnt/datahdd/drone/cache
