kind: pipeline
type: docker
name: default
platform:
    os:   linux
    arch: arm64

volumes:
    -   name: cache
        host:
            path: /mnt/datahdd/drone/cache

trigger:
    event: [ push, pull_request ]
    branch: [ main ]

steps:
    -   name:  restore cache
        image: meltwater/drone-cache
        settings:
            backend: "filesystem"
            restore: true
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache

    -   name:  .npmrc
        image: busybox
        environment:
            GITHUB_TOKEN:
                from_secret: GITHUB_TOKEN
        commands:
            - echo "@dasred:registry=https://npm.pkg.github.com/" > .npmrc
            - echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc

    -   name:  npm install
        image: node:18-alpine
        commands:
            - npm i

    -   name:  release
        image: node:18-alpine
        environment:
            GITHUB_TOKEN:
                from_secret: GITHUB_TOKEN
        commands:
            - apk update && apk upgrade && apk add --no-cache git
#            - npm set registry "https://npm.pkg.github.com/"
#            - npm set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
            - npm publish

    -   name:  rebuild cache
        image: meltwater/drone-cache
        settings:
            backend: "filesystem"
            rebuild: true
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache
        when:
            status:
                - success
                - failure
