kind: pipeline
type: docker
name: default
platform:
    os:   linux
    arch: arm64

steps:
    -   name:  restore cache
        image: meltwater/drone-cache
        settings:
            pull:    true
            backend: "filesystem"
            restore: true
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache

    -   name:  npm install
        image: node:18-alpine
        when:
            branch:
                - main
        commands:
            - npm i

    -   name:  release
        image: node:18-alpine
        when:
            branch:
                - main
        environment:
            GITHUB_TOKEN:
                from_secret: GITHUB_TOKEN
        commands:
            - apk update && apk upgrade && apk add --no-cache git
            - echo "@dasred:registry=https://npm.pkg.github.com/" > .npmrc
            - echo "//npm.pkg.github.com/:_authToken=\"$GITHUB_TOKEN\"" >> .npmrc
            - npm set @dasred:registry https://npm.pkg.github.com
            - npm publish

    -   name:  rebuild cache
        image: meltwater/drone-cache
        settings:
            pull:    true
            backend: "filesystem"
            rebuild: true
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache
        when:
            status:
                - success
                - failure

volumes:
    -   name: cache
        host:
            path: /mnt/datahdd/drone/cache
